name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        id: setup-vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: efb1e7436979a30c4d3e5ab2375fd8e2e461d541

      - name: Cache CMake binaries
        uses: actions/cache@v4
        with:
          path: out/build/linux-release
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-
      
      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        env:
          MQTT_SERVER: "tcp://broker.emqx.io:1883"
          MQTT_TOPIC: "test/topic"
          MQTT_QOS: "1"
          MQTT_CLIENT_ID: "test_client"
        with:
          configurePreset: "linux-release"
          configurePresetAdditionalArgs: "['-DENABLE_TESTING=ON']"
          buildPreset: "linux-release"
          testPreset: "linux-release"
          testPresetAdditionalArgs: "['--output-on-failure']"
          packagePreset: "linux-release"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: out/build/linux-release/CPP-MQTTClient*