name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mosquitto:
        image: eclipse-mosquitto:latest
        options: >-
          --name mosquitto
          -p 30520:1883
          -v "$(pwd)/docker/mosquitto/config:/mosquitto/config"
          -v "$(pwd)/docker/mosquitto/data:/mosquitto/data"
          -v "$(pwd)/docker/mosquitto/log:/mosquitto/log"
        ports:
          - 30520:1883
        env:
          - "MOSQUITTO_CONFIG_PATH=/mosquitto/config/mosquitto.conf"
        # Ensure the container starts in the background and is available for the test
        entrypoint: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf -v

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        id: setup-vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: efb1e7436979a30c4d3e5ab2375fd8e2e461d541

      - name: Cache CMake binaries
        uses: actions/cache@v4
        with:
          path: out/build/linux-release
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Wait for Mosquitto to start
        run: |
          sleep 5
      
      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "linux-release"
          configurePresetAdditionalArgs: "['-DENABLE_TESTING=ON']"
          buildPreset: "linux-release"
          testPreset: "linux-release"
