name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache vcpkg binaries
      uses: actions/cache@v2
      with:
        path: ~/.cache/vcpkg
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Set up vcpkg
      uses: microsoft/setup-vcpkg@v1
      with:
        vcpkgGitCommitId: efb1e7436979a30c4d3e5ab2375fd8e2e461d541

    - name: Install dependencies
      run: vcpkg install paho-mqttpp3

    - name: Cache CMake binaries
      uses: actions/cache@v2
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Configure CMake
      run: cmake -B build -S . -DENABLE_ADDRESS_SANITIZER=OFF

    - name: Build
      run: cmake --build build --config Release